spring:
  application:
    name: order-process
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: order-processing-group  # DIFFERENT group → receives all messages too
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 50
      heartbeat-interval-ms: 3000
      session-timeout-ms: 10000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.spring.poc.kafka.model
        spring.json.use.type.headers: true   # One Topic Multiple Event Types
    listener:
      concurrency: 3
      ack-mode: record
      missing-topics-fatal: false
      poll-timeout: 3000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true

server:
  port: 8082

kafka:
  topic: orders
  dlt:
    topic: orders.DLQ

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics