version: '3.8'

services:

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry

    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: |
        PLAINTEXT://kafka1:29092,PLAINTEXT://kafka2:29092,PLAINTEXT://kafka3:29092

    networks:
      - kafka-network

  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    container_name: kafka-rest
    hostname: kafka-rest

    ports:
      - "${KAFKA_REST_PORT}:8082"

    depends_on:
      - schema-registry

    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082

      KAFKA_REST_BOOTSTRAP_SERVERS: |
        PLAINTEXT://kafka1:29092,PLAINTEXT://kafka2:29092,PLAINTEXT://kafka3:29092

      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081

    networks:
      - kafka-network

networks:
  kafka-network:
    external: true