spring:
  application:
    name: alert-notification
  lifecycle:
    timeout-per-shutdown-phase: 20s
  kafka:
    bootstrap-servers: ${KAFKA_EXTERNAL_HOST:localhost}:9092,${KAFKA_EXTERNAL_HOST:localhost}:9093,${KAFKA_EXTERNAL_HOST:localhost}:9094
    consumer:
      group-id: alert-notification-group  # DIFFERENT group → receives all messages too
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:7074}
        specific.avro.reader: true
        # Enable DLT (Dead letter topic) support
        isolation.level: read_committed
      max-poll-records: 100
      max-poll-interval-ms: 300000
    listener:
      concurrency: 3
      ack-mode: record

app:
  alerts:
    high-value-threshold: ${APP_HIGH_VALUE_THRESHOLD:1000.0}
  kafka:
    topics:
      order-events: order-events

server:
  port: 8083
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,springwolf
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springwolf:
  enabled: true
  docket:
    base-package: com.spring.poc.kafka
    info:
      title: Alert Notification Service
      version: 1.0.0
      description: >-
        Alert notification service that consumes alert events from alert-events topic(Kafka)
        This service acts as consumer, receiving alert events from alert-events topic and processing alert state transition for downstream services to consume
        Includes Dead letter topic (DLT) support for handling failed messages.
    servers:
      local:
        host: localhost:9092
        protocol: kafka
        description: Local Development Kafka cluster
      docker-compose:
        host: kafka:29093
        protocol: kafka
        description: Docker Compose Kafka Service