spring:
  application:
    name: alert-notification
  kafka:
    bootstrap-servers: ${KAFKA_EXTERNAL_HOST:localhost}:9092,${KAFKA_EXTERNAL_HOST:localhost}:9093,${KAFKA_EXTERNAL_HOST:localhost}:9094
    consumer:
      group-id: alert-notification-group  # DIFFERENT group → receives all messages too
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:7074}
        specific.avro.reader: true
    listener:
      concurrency: 3

app:
  kafka:
    topics:
      order-events: order-events

server:
  port: 8083